permalink: /:categories/:title.html
url: "https://kerivietnam.github.io"
full_name: "Your Full Name"
first_name: "First Name"
last_name: "Last Name"
blog_title: "Blog title "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "keri vietnam"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Ghosteyes1"
github: "kerivietnam"
facebook: "mepasindu"
linkined_url: ""
